GET http://localhost:3000/api/doctext

###

POST http://localhost:3000/api/doctext
Content-Type: application/json

{
  "product_name": "new doc",
  "text_field": "doc texttt",
  "text_color": "black",
  "bg_color": "purple"
}

###

PUT http://localhost:3000/api/doctext 
Content-Type: application/json

{
  "product_id": 2, 
  "product_name": "Updated text",
  "text_field": "This is some text 3...", 
  "text_color": "red",
  "bg_color": "black",
  "date": ""
}

###

DELETE http://localhost:3000/api/doctext 
Content-Type: application/json

{
  "product_id": 17
}

###