import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Main from "./components/Main";
import { DocProvider } from "./components/DocContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DocProvider>
        <body className=" bg-slate-900">
          <Header />
          <div>
            <Main>{children}</Main>
          </div>
        </body>
      </DocProvider>
    </html>
  );
}
